

# ============================================================
# ENTERPRISE API DISCOVERY, RISK & ANALYTICS PLATFORM
# FIXED VERSION WITH JSON/CSV UPLOAD & RESET
# Designed & Developed by Randy Singh – KNet Consulting Group
# ============================================================

import streamlit as st
import random
import json
import pandas as pd
import matplotlib.pyplot as plt
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
import tempfile

# ---------------------------
# Page Configuration
# ---------------------------
st.set_page_config(
    page_title="Enterprise API Discovery",
    page_icon="🔐",
    layout="wide"
)

st.title("🔐 Enterprise API Discovery & Risk Analytics Platform")
st.markdown(
    "Automatically discover APIs from traffic, assess risk exposure, "
    "and generate executive-ready security reports."
)

# ---------------------------
# Mock API Data Generator
# ---------------------------
def generate_mock_api_data(num_records=150):
    data = []
    for i in range(1, num_records + 1):
        method = random.choice(["GET", "POST", "PUT", "DELETE", "PATCH"])
        version = random.choice(["v1", "v2", "v3"])
        auth = random.choice(["OAuth", "API Key", "None"])
        endpoint = f"/api/{version}/resource/{random.randint(1, 100)}"

        data.append({
            "id": i,
            "http_method": method,
            "endpoint": endpoint,
            "authentication": auth
        })
    return pd.DataFrame(data)

# ---------------------------
# API Discovery Function
# ---------------------------
def discover_apis(df):
    discovered = {}
    for _, row in df.iterrows():
        ep = row["endpoint"]
        version = ep.split("/")[2]
        if ep not in discovered:
            discovered[ep] = {
                "version": version,
                "authentication": row["authentication"],
                "http_methods": set([row["http_method"]])
            }
        else:
            discovered[ep]["http_methods"].add(row["http_method"])

    # Convert sets to lists
    for ep in discovered:
        discovered[ep]["http_methods"] = list(discovered[ep]["http_methods"])
    return discovered

# ---------------------------
# Risk Scoring
# ---------------------------
def calculate_risk(http_methods, authentication):
    score = 0
    if authentication == "None":
        score += 50
    elif authentication == "API Key":
        score += 25
    elif authentication == "OAuth":
        score += 10

    if "DELETE" in http_methods:
        score += 20
    if "PUT" in http_methods or "PATCH" in http_methods:
        score += 10
    if len(http_methods) > 3:
        score += 10

    if score >= 70:
        level = "High"
    elif score >= 40:
        level = "Medium"
    else:
        level = "Low"

    return score, level

# ---------------------------
# PDF Report
# ---------------------------
def generate_pdf(df):
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    doc = SimpleDocTemplate(tmp.name, pagesize=LETTER)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("<b>Enterprise API Discovery & Risk Report</b>", styles["Title"]))
    elements.append(Paragraph("Generated by KNet Consulting Group", styles["Normal"]))

    table_data = [df.columns.tolist()] + df.values.tolist()
    table = Table(table_data, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
        ("GRID", (0,0), (-1,-1), 0.5, colors.black),
        ("ALIGN", (0,0), (-1,-1), "CENTER")
    ]))
    elements.append(table)
    doc.build(elements)
    return tmp.name

# ---------------------------
# File Loader (CSV or JSON)
# ---------------------------
def load_uploaded_file(uploaded_file):
    if uploaded_file is None:
        return None
    try:
        if uploaded_file.name.lower().endswith(".csv"):
            df = pd.read_csv(uploaded_file)
        elif uploaded_file.name.lower().endswith(".json"):
            df = pd.read_json(uploaded_file)
        else:
            st.error("Unsupported file type. Upload CSV or JSON.")
            return None
        return df
    except Exception as e:
        st.error(f"Error loading file: {e}")
        return None

# ---------------------------
# Sidebar Controls
# ---------------------------
st.sidebar.header("⚙️ Controls")

records = st.sidebar.slider("Number of Synthetic Records", 50, 500, 150, 50)
uploaded_file = st.sidebar.file_uploader("Upload API Data (CSV or JSON)", type=["csv", "json"])
reset_btn = st.sidebar.button("🔄 Reset / Generate Data")

# ---------------------------
# Main Logic
# ---------------------------
if reset_btn:
    # Generate new synthetic data
    df = generate_mock_api_data(records)
    st.success(f"Synthetic API data generated ({len(df)} records)")
elif uploaded_file is not None:
    df = load_uploaded_file(uploaded_file)
    if df is not None:
        st.success(f"Uploaded {len(df)} records successfully!")
else:
    df = None
    st.info("Upload a CSV/JSON file or generate synthetic data to begin analysis.")

if df is not None:
    # Discover APIs
    discovered = discover_apis(df)

    # Prepare discovery DataFrame with risk scoring
    rows = []
    for ep, details in discovered.items():
        risk_score, risk_level = calculate_risk(details["http_methods"], details["authentication"])
        rows.append({
            "Endpoint": ep,
            "Version": details["version"],
            "HTTP Methods": ", ".join(details["http_methods"]),
            "Authentication": details["authentication"],
            "Risk Score": risk_score,
            "Risk Level": risk_level
        })
    discovery_df = pd.DataFrame(rows)

    # ---------------------------
    # Metrics
    # ---------------------------
    st.subheader("📊 Summary Metrics")
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total API Calls", len(df))
    c2.metric("Unique APIs", len(discovery_df))
    c3.metric("High-Risk APIs", (discovery_df["Risk Level"]=="High").sum())
    c4.metric("Unauthenticated APIs", (discovery_df["Authentication"]=="None").sum())

    # ---------------------------
    # Tables
    # ---------------------------
    st.subheader("🧪 API Traffic Sample")
    st.dataframe(df.head(20), use_container_width=True)

    st.subheader("🔍 Discovered APIs with Risk Scoring")
    st.dataframe(discovery_df, use_container_width=True)

    # ---------------------------
    # Charts
    # ---------------------------
    st.subheader("📈 Analytics & Risk Visualization")
    col1, col2, col3 = st.columns(3)

    with col1:
        fig, ax = plt.subplots()
        discovery_df["Risk Level"].value_counts().plot(kind="bar", ax=ax, color=["red","orange","green"])
        ax.set_title("API Risk Distribution")
        st.pyplot(fig)

    with col2:
        fig, ax = plt.subplots()
        df["http_method"].value_counts().plot(kind="pie", autopct="%1.0f%%", ax=ax)
        ax.set_ylabel("")
        ax.set_title("HTTP Method Usage")
        st.pyplot(fig)

    with col3:
        fig, ax = plt.subplots()
        df["authentication"].value_counts().plot(kind="bar", ax=ax, color=["green","orange","red"])
        ax.set_title("Authentication Types")
        st.pyplot(fig)

    # ---------------------------
    # Downloads
    # ---------------------------
    st.subheader("📥 Export Reports")

    json_report = json.dumps({"mock_data": df.to_dict(orient="records"), "discovered_apis": discovered}, indent=4)
    st.download_button("⬇️ Download JSON Report", json_report, "api_discovery_report.json", "application/json")

    pdf_path = generate_pdf(discovery_df)
    with open(pdf_path, "rb") as f:
        st.download_button("⬇️ Download PDF Report", f, "api_discovery_risk_report.pdf", "application/pdf")

    # ---------------------------
    # Recommendations
    # ---------------------------
    st.subheader("🧠 Security Recommendations")
    st.markdown(
        """
        - Enforce **OAuth 2.0** on all production APIs  
        - Restrict **DELETE / PUT** methods where not required  
        - Monitor high-risk APIs continuously  
        - Implement API gateways and rate-limiting  
        - Maintain version lifecycle governance  
        """
    )

# ---------------------------
# Footer
# ---------------------------
st.markdown("---")
st.markdown("**Enterprise API Discovery Platform** | © KNet Consulting Group | Randy Singh")
