

# ============================================================
# ENTERPRISE API DISCOVERY, RISK & ANALYTICS PLATFORM
# Designed & Developed by Randy Singh – KNet Consulting Group
# ============================================================

import streamlit as st
import random
import json
import pandas as pd
import matplotlib.pyplot as plt
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import LETTER
from reportlab.lib import colors
import tempfile

# ------------------------------------------------------------
# Page Configuration
# ------------------------------------------------------------
st.set_page_config(
    page_title="Enterprise API Discovery Platform",
    page_icon="🔐",
    layout="wide"
)

# Title Bar with subtitle
st.markdown('<h1 style="color:#0B5ED7; font-weight:bold;">🔐 Enterprise API Discovery, Risk & Analytics Platform</h1>', unsafe_allow_html=True)
st.markdown('<h4 style="border-bottom:2px solid #0B5ED7; padding-bottom:5px;">Developed by Randy Singh – Kalsnet (KNet) Consulting Group</h4>', unsafe_allow_html=True)
st.markdown("---")

# ------------------------------------------------------------
# Session State for Data
# ------------------------------------------------------------
if "mock_data" not in st.session_state:
    st.session_state.mock_data = None
if "discovery_df" not in st.session_state:
    st.session_state.discovery_df = None
if "uploaded_file" not in st.session_state:
    st.session_state.uploaded_file = None

# ------------------------------------------------------------
# Sidebar Controls
# ------------------------------------------------------------
st.sidebar.header("⚙️ Controls")

records = st.sidebar.slider("Number of Synthetic API Records", 50, 500, 150, 50)

uploaded_file = st.sidebar.file_uploader(
    "Upload Your API Log File (.csv/.txt)",
    type=["txt", "csv"]
)

if st.sidebar.button("🔄 Reset Data"):
    st.session_state.mock_data = None
    st.session_state.discovery_df = None
    st.session_state.uploaded_file = None
    st.experimental_rerun()

run_btn = st.sidebar.button("🚀 Run Discovery & Risk Analysis")

# ------------------------------------------------------------
# Mock API Data Generator
# ------------------------------------------------------------
def generate_mock_api_data(num_records=150):
    data = []
    for i in range(1, num_records + 1):
        method = random.choice(["GET", "POST", "PUT", "DELETE", "PATCH"])
        version = random.choice(["v1", "v2", "v3"])
        auth = random.choice(["OAuth", "API Key", "None"])
        endpoint = f"/api/{version}/resource/{random.randint(1, 100)}"
        data.append({
            "id": i,
            "http_method": method,
            "endpoint": endpoint,
            "authentication": auth
        })
    return data

# ------------------------------------------------------------
# API Discovery
# ------------------------------------------------------------
def discover_apis(mock_data):
    discovered = {}
    for r in mock_data:
        ep = r["endpoint"]
        version = ep.split("/")[2]
        if ep not in discovered:
            discovered[ep] = {
                "version": version,
                "authentication": r["authentication"],
                "http_methods": set([r["http_method"]])
            }
        else:
            discovered[ep]["http_methods"].add(r["http_method"])
    for ep in discovered:
        discovered[ep]["http_methods"] = list(discovered[ep]["http_methods"])
    return discovered

# ------------------------------------------------------------
# API Risk Scoring Engine
# ------------------------------------------------------------
def calculate_risk(http_methods, authentication):
    score = 0
    if authentication == "None":
        score += 50
    elif authentication == "API Key":
        score += 25
    elif authentication == "OAuth":
        score += 10
    if "DELETE" in http_methods:
        score += 20
    if "PUT" in http_methods or "PATCH" in http_methods:
        score += 10
    if len(http_methods) > 3:
        score += 10
    if score >= 70:
        level = "High"
    elif score >= 40:
        level = "Medium"
    else:
        level = "Low"
    return score, level

# ------------------------------------------------------------
# PDF Report Generator
# ------------------------------------------------------------
def generate_pdf(discovery_df):
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    doc = SimpleDocTemplate(tmp.name, pagesize=LETTER)
    styles = getSampleStyleSheet()
    elements = []
    elements.append(Paragraph("<b>Enterprise API Discovery & Risk Report</b>", styles["Title"]))
    elements.append(Paragraph("Generated by KNet Consulting Group", styles["Normal"]))
    table_data = [discovery_df.columns.tolist()] + discovery_df.values.tolist()
    table = Table(table_data, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
        ("GRID", (0,0), (-1,-1), 0.5, colors.black),
        ("ALIGN", (0,0), (-1,-1), "CENTER")
    ]))
    elements.append(table)
    doc.build(elements)
    return tmp.name

# ------------------------------------------------------------
# Load Uploaded File
# ------------------------------------------------------------
def load_uploaded_file(uploaded_file):
    if uploaded_file.name.endswith(".csv"):
        df = pd.read_csv(uploaded_file)
    else:
        # Assuming txt file in format: id,http_method,endpoint,authentication
        df = pd.read_csv(uploaded_file, sep=",")
    return df.to_dict(orient="records")

# ------------------------------------------------------------
# Main Execution
# ------------------------------------------------------------
if run_btn:
    if uploaded_file:
        st.session_state.uploaded_file = uploaded_file
        mock_data = load_uploaded_file(uploaded_file)
    else:
        mock_data = generate_mock_api_data(records)
    
    st.session_state.mock_data = mock_data
    discovered = discover_apis(mock_data)

    mock_df = pd.DataFrame(mock_data)

    rows = []
    for ep, d in discovered.items():
        risk_score, risk_level = calculate_risk(d["http_methods"], d["authentication"])
        rows.append({
            "Endpoint": ep,
            "Version": d["version"],
            "HTTP Methods": ", ".join(d["http_methods"]),
            "Authentication": d["authentication"],
            "Risk Score": risk_score,
            "Risk Level": risk_level
        })
    discovery_df = pd.DataFrame(rows)
    st.session_state.discovery_df = discovery_df

    # --------------------------------------------------------
    # Metrics
    # --------------------------------------------------------
    st.subheader("📊 Executive Summary")
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total API Calls", len(mock_df))
    c2.metric("Unique APIs", len(discovery_df))
    c3.metric("High-Risk APIs", (discovery_df["Risk Level"]=="High").sum())
    c4.metric("Unauthenticated APIs", (discovery_df["Authentication"]=="None").sum())

    # --------------------------------------------------------
    # Tables
    # --------------------------------------------------------
    st.subheader("🧪 API Traffic Sample")
    st.dataframe(mock_df.head(20), use_container_width=True)

    st.subheader("🔍 Discovered APIs with Risk Scoring")
    st.dataframe(discovery_df, use_container_width=True)

    # --------------------------------------------------------
    # Charts
    # --------------------------------------------------------
    st.subheader("📈 Analytics & Risk Visualization")
    col1, col2, col3 = st.columns(3)
    with col1:
        fig, ax = plt.subplots()
        discovery_df["Risk Level"].value_counts().plot(kind="bar", ax=ax)
        ax.set_title("API Risk Distribution")
        st.pyplot(fig)
    with col2:
        fig, ax = plt.subplots()
        mock_df["http_method"].value_counts().plot(kind="pie", autopct="%1.0f%%", ax=ax)
        ax.set_ylabel("")
        ax.set_title("HTTP Method Usage")
        st.pyplot(fig)
    with col3:
        fig, ax = plt.subplots()
        mock_df["authentication"].value_counts().plot(kind="bar", ax=ax)
        ax.set_title("Authentication Types")
        st.pyplot(fig)

    # --------------------------------------------------------
    # Downloads
    # --------------------------------------------------------
    st.subheader("📥 Export Reports")
    json_report = json.dumps({"mock_data": mock_data, "discovered_apis": discovered}, indent=4)
    st.download_button("⬇️ Download JSON Report", json_report, "api_discovery_report.json", "application/json")

    pdf_path = generate_pdf(discovery_df)
    with open(pdf_path, "rb") as f:
        st.download_button("⬇️ Download Executive PDF Report", f, "api_discovery_risk_report.pdf", "application/pdf")

    # --------------------------------------------------------
    # Recommendations
    # --------------------------------------------------------
    st.subheader("🧠 Security Recommendations")
    st.markdown(
        """
        - Enforce **OAuth 2.0** on all production APIs  
        - Restrict **DELETE / PUT** methods where not required  
        - Monitor high-risk APIs continuously  
        - Implement API gateways and rate-limiting  
        - Maintain version lifecycle governance  
        """
    )
else:
    st.info("Use the sidebar to generate synthetic API records or upload your own log file to run discovery and risk analysis.")
