OPENAI_API_KEY="sk-proj-ZgRIvaE8G4AMR0Oc39a9NsbztgYu8tx3VkhBexJGXul4Me4XdHm1XSYF02fI1NJ1MWA05_-icOT3BlbkFJBdVECSifcDGF1wOt2Gp4IneIQDTToP7VNHC3tTcSB0R-pJQxYN_2WFLiYjqj4BDtiyclq135AAx"
GROQ_API_KEY ="gsk_xxxxxxxxxxxxxxxx"
CLAUDE_API_KEY ="sk-ant-xxxxxxxxxxxx"
MISTRAL_API_KEY ="xxxxxxxxxxxxxxxx"

